baseurl = "https://hypery2k.github.io" # Hostname (and path) to the root.
title = "Martin Reinhardt" # Site title.
theme = "coder" # Set the theme.
languagecode = "en-US" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsUseClasses=true
pygmentscodefences = false # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Martin Reinhardt" # Author's name.
    info = "Ambassador of Software Craftsmanship and {Code} Catalyst" # Author's job title or info.
    description = "Martin Reinhardt's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "https://i.stack.imgur.com/Wx8Bi.png?s=328&g=1" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = false

    # Custom CSS
    custom_css = ['/css/styles.css']

    # RTL support
    rtl = false

# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 1
    url = "https://twitter.com/mreinhardt/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/hypery2k/"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow"
    weight = 3
    url = "https://stackoverflow.com/users/2490834/hypery2k?tab=profile"
[[params.social]]
    name = "Packt Publishing"
    icon = "fab fa-graduation-cap"
    weight = 4
    url = "https://www.packtpub.com/books/info/authors/martin-reinhardt"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@mreinhardt"
[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube"
    weight = 6
    url = "https://www.youtube.com/playlist?list=PL2bgi8_0R1dFZ9DNpp3Wxnl07eLh8Edr-"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase"
    weight = 7
    url = "https://keybase.io/hypery2k"
[[params.social]]
    name = "CV"
    icon = "fas fa-user-tie"
    weight = 8
    url = "http://martinreinhardt-online.de/en/cv/resume.html"
[[params.social]]
    name = "Homepage"
    icon = "fab fa-html5"
    weight = 9
    url = "https://martinreinhardt-online.de"
# Menu links
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
